class PaymentMethod:

    AFTERPAY = 'AFTERPAY'
    ALIPAY = 'ALIPAY'
    BANCONTACT = 'MISTERCASH'
    BANKTRANSFER = 'BANKTRANS'
    BELFIUS = 'BELFIUS'
    CREDITCARD = 'CREDITCARD'
    DIRECTDEBIT = 'DIRDEB'
    DOTPAY = 'DOTPAY'
    EINVOICING = 'EINVOICE'
    EPS = 'EPS'
    GIROPAY = 'GIROPAY'
    IDEAL = 'IDEAL'
    IDEALQR = 'IDEALQR'
    INGHOMEPAY = 'INGHOME'
    KBC = 'KBC'
    KLARNA = 'KLARNA'
    PAYPAL = 'PAYPAL'
    SANTANDER = 'SANTANDER'
    SOFORT = 'DIRECTBANK'
    TRUSTLY = 'TRUSTLY'
    PAYAFTER = 'PAYAFTER'






